CREATE DATABASE VENTA_DE_ROPA;
USE VENTA_DE_ROPA;

CREATE TABLE VENTA_DE_ROPA(
    VDR_ID INT,
    VDR_NOMBRE VARCHAR(100) not null
    VDR_PRECIO NUMBER
);
ALTER TABLE VENTA_DE_ROPA(
    add constrain pk_ID Primary Key (VDR_ID)
);

CREATE TABLE STOCK(
 STO_ID NUMBER not null,
 STO_CANT number
 STO_VDR_ID number
);
ALTER TABLE STOCKS(
    PRIMARY KEY (STO_ID)
     FOREING KEY (STO_VDR_ID) REFENCE VENTA_DE_ROPA(VDR_ID) 
);
INSERT INTO VDR (VDR_ID,VDR_NOMBRE,VDR_PRECIO)
  VALUES (1,`jeens`,20.000)
INSERT INTO VDR (VDR_ID,VDR_NOMBRE,VDR_PRECIO)
  VALUES (2,`remera`,15.000)
INSERT INTO VDR (VDR_ID,VDR_NOMBRE,VDR_PRECIO)
  VALUES (3`CAMPERA`,35.000)
 
INSERT INTO STOCK(STO_ID,STO_CAN,STO_VDR_ID) 
 VALUES (`1`,25,1)
INSERT INTO STOCK(STO_ID,STO_CAN,STO_VDR_ID)
VALUES (`2`,10,2)
INSERT INTO STOCK(STO_ID,STO_CAN,STO_VDR_ID)
VALUES (`3`,5,3)
